PANDAS

In [2]:
import sys
print(sys.executable)

c:\Users\sanja\AppData\Local\Programs\Python\Python313\python.exe

In [3]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\sanja\appdata\local\programs\python\python313\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sanja\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sanja\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sanja\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\sanja\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("Retail_Dataset_Modified.csv")

In [6]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [7]:
df.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

Difference between List & Array

1.List

In [8]:
list1=[1,2,3]
list2=[4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]

2.Array

In [ ]:
import numpy as np

arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])
print(arr1+arr2)

[5 7 9]
[1, 2, 3, 4, 5, 6]

In [21]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(5171, 47)

In [22]:
print("Columns:")
print(df.columns)

Columns:
Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [23]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   str
 1   Store_Name             5171 non-null   str
 2   Brand_Name             5171 non-null   str
 3   Store_Type             5171 non-null   str
 4   City                   5109 non-null   str
 5   City_Tier              5171 non-null   str
 6   Product_Name           5098 non-null   str
 7   Category               5171 non-null   str
 8   Sub_Category           5171 non-null   str
 9   Product_Stage          5171 non-null   str
 10  Quantity_Available     5171 non-null   str
 11  Units_Sold             5171 non-null   str
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   str
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   str
 20  Sales_Channel          5171 non-null   str
 21  Payment_Method         5171 non-null   str
 22  Supplier               5103 non-null   str
 23  Supplier_Rating        5171 non-null   str
 24  Promotion_Type         5171 non-null   str
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   str
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   str
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   str
 40  Weather_Impact         5171 non-null   str
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   str
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   str
 46  Season                 5171 non-null   str
dtypes: float64(11), int64(10), str(26)
memory usage: 1.9 MB
None

In [24]:
df

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

Create Numpy Array

In [25]:
Category_Array=np.array(df['Category'])
Category_Array

array(['Groceries', 'Groceries', 'Clothes', ..., 'Electronics', 'Clothes',
       'Electronics'], shape=(5171,), dtype=object)

In [27]:
StoreID_Array=np.array(df["Store_ID"])
StoreID_Array

array(['BX_PUNE_034', 'BX_MUMBAI_023', 'BX_PUNE_073', ...,
       'BX_KANPUR_097', 'BX_MUMBAI_031', 'BX_DELHI_032'],
      shape=(5171,), dtype=object)

In [29]:
Store_Name=np.array(df["Store_Name"])
Store_Name

array(['BrandX_India Superstore Pune', 'BrandX_India Superstore Mumbai',
       'BrandX_India Trends Pune', ..., 'BrandX_India Gadget Zone Kanpur',
       'BrandX_India Style Mumbai', 'BrandX_India Electronics Delhi'],
      shape=(5171,), dtype=object)

In [30]:
Product_Name_Array=np.array(df["Product_Name"])
Product_Name_Array

array(['Green Tea 100g', 'White Sugar 1kg', "Levi's T-Shirt", ...,
       'Dell XPS 13', 'Nike Air Max', 'MacBook Air M2'],
      shape=(5171,), dtype=object)

In [31]:
revenue_array = np.array(df["Revenue"])
print(revenue_array)

['7320' '1645' '66340' ... '982202' '244244' '1408680']

In [33]:
brand_array=np.array(df["Brand_Name"])
brand_array

array(['BrandX_India', 'BrandX_India', 'BrandX_India', ...,
       'BrandX_India', 'BrandX_India', 'BrandX_India'],
      shape=(5171,), dtype=object)

Access the First Revenue Value Using Indexing

In [34]:
print("First Revenue Value:")
print(revenue_array[0])

First Revenue Value:
7320

Access the Last Revenue Value

In [35]:
print("Last Revenue Value:")
print(revenue_array[-1])

Last Revenue Value:
1408680

Slice the First Five Revenue Records

In [36]:
print("First Five Revenue Values:")
print(revenue_array[0:5])

First Five Revenue Values:
['7320' '1645' '66340' '77748' '1976364']

Slice Revenue Values from Index 10 to 20

In [37]:
print("Revenue Values from Index 10 to 20:")
print(revenue_array[10:21])

Revenue Values from Index 10 to 20:
['318948' '25636' '3893616' '375382' '118697' '544334' '144100' '5363'
 '4894784' '116721' '2264131']

Create a Two-Dimensional Array

In [38]:
sales_array = np.array(df[["Units_Sold", "Profit_Margin"]])

print(sales_array)

[['24' 21.64]
 ['35' 29.79]
 ['31' 19.86]
 ...
 ['13' 29.86]
 ['22' 16.53]
 ['12' 29.34]]

Access the First Row of the Array

In [39]:
print("First Row:")
print(sales_array[0])

First Row:
['24' 21.64]

Access the Profit Margin Column

In [40]:
print("Profit Margin Column:")
print(sales_array[:,1])

Profit Margin Column:
[21.64 29.79 19.86 ... 29.86 16.53 29.34]

Task 2: Perform Operations

Display the First 10 Revenue Values

In [41]:
first_ten = revenue_array[0:10]
print(first_ten)

['7320' '1645' '66340' '77748' '1976364' '18511' '3026641' '4860270'
 '870570' '35552']

Find Total Revenue of First 10 Records

In [42]:
print("Total Revenue:")
print(np.sum(first_ten))

Total Revenue:
7320164566340777481976364185113026641486027087057035552

Find Highest Revenue from First 10 Records

In [43]:
print("Maximum Revenue:")
print(np.max(first_ten))

Maximum Revenue:
870570

Find Lowest Revenue from First 10 Records

In [44]:
print("Lowest Revenue:")
print(np.min(first_ten))

Lowest Revenue:
1645